@host = http://localhost:3000

### POST form data
POST {{host}}/submitForm
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123456

------WebKitFormBoundary123456
Content-Disposition: form-data; name="name"

Alice Johnson
------WebKitFormBoundary123456
Content-Disposition: form-data; name="email"

alice@example.com
------WebKitFormBoundary123456--

#### Assert: Check form data submission
Status: 201
Content-Type: application/json
Body:
$.name: Alice Johnson
$.email: alice@example.com

# ### POST file upload
# POST {{host}}/upload
# Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123456

# ------WebKitFormBoundary123456
# Content-Disposition: form-data; name="file"; filename="attachfile.data"
# Content-Type: application/octet-stream

# < ./attachfile.data
# ------WebKitFormBoundary123456--

# #### Assert: Check file upload
# Status: 201