import { HttpRequest } from "../types";
import { VariableManager } from "./VariableManager";
export declare class HttpFileParser {
    private variableManager;
    private parsedCustomAssertions;
    private currentRequest;
    private currentTest;
    private isParsingBody;
    private bodyContent;
    constructor(variableManager: VariableManager);
    parse(filePath: string): Promise<HttpRequest[]>;
    private parseRequests;
    private resetParserState;
    private parseLine;
    private isComment;
    private handleVariable;
    private isRequestStart;
    private startNewRequest;
    private finishCurrentRequest;
    private createNewRequest;
    private isTestStart;
    private startNewTest;
    private createNewTest;
    private parseRequestLine;
    private isHttpMethod;
    private setRequestMethod;
    private handleKeyValuePair;
    private handleTestLine;
    private parseAssertion;
    private parseValue;
    private parseJsonBody;
    private isInsideQuotes;
}
